spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cars_info_db
    username: postgres
    password: "123456789"
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        ddl-auto: create-drop
        temp:
          use_jdbc_metadata_defaults: false
    javax:
      persistence:
        schema-generation:
          scripts:
            action: create
            create-target: create.sql
            create-source: metadata

  logging:
    level:
      root: INFO
      com.mycompany.myapp: DEBUG
